In [1]:
import mne 
import pandas as pd
import numpy as np
import os
import matplotlib

In [23]:
run_04.save("/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg_updated.fif", overwrite=True)


Writing /Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg_updated.fif


/var/folders/14/1wp2gs4s4k9094qkx6kvfvq00000gn/T/ipykernel_1017/629565230.py:1: RuntimeWarning: This filename (/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg_updated.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  run_04.save("/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg_updated.fif", overwrite=True)


Closing /Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg_updated.fif
[done]


In [25]:
run_04=mne.io.read_raw_fif('/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg.fif',allow_maxshield=True)

Opening raw data file /Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg.fif...
    Read a total of 13 projection items:
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
    Range : 16000 ... 402999 =     16.000 ...   402.999 secs
Ready.


/var/folders/14/1wp2gs4s4k9094qkx6kvfvq00000gn/T/ipykernel_1017/1003639823.py:1: RuntimeWarning: This file contains raw Internal Active Shielding data. It may be distorted. Elekta recommends it be run through MaxFilter to produce reliable results. Consider closing the file and running MaxFilter on the data.
  run_04=mne.io.read_raw_fif('/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg.fif',allow_maxshield=True)


In [29]:
print(run_04.info['dev_head_t'])

<Transform | MEG device->head>
[[ 0.98263299 -0.17270018 -0.06788003  0.00073212]
 [ 0.18380286  0.95610273  0.2282207   0.01309432]
 [ 0.02548652 -0.23673365  0.97124064  0.06388994]
 [ 0.          0.          0.          1.        ]]


In [19]:
# Copy dev_head_t from run-03 to run-04
run_04.info['dev_head_t'] = run_05.info['dev_head_t']

# Verify the new dev_head_t in run-04
print("Updated dev_head_t for run-04:", run_04.info['dev_head_t'])


Updated dev_head_t for run-04: <Transform | MEG device->head>
[[ 0.98263299 -0.17270018 -0.06788003  0.00073212]
 [ 0.18380286  0.95610273  0.2282207   0.01309432]
 [ 0.02548652 -0.23673365  0.97124064  0.06388994]
 [ 0.          0.          0.          1.        ]]


In [15]:
run_04=mne.io.read_raw_fif('/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg.fif',allow_maxshield=True)
run_05=mne.io.read_raw_fif('/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-05_meg.fif',allow_maxshield=True,preload=True)


Opening raw data file /Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg.fif...
    Read a total of 13 projection items:
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
    Range : 16000 ... 402999 =     16.000 ...   402.999 secs
Ready.
Opening raw data file /Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-05_meg.fif..

/var/folders/14/1wp2gs4s4k9094qkx6kvfvq00000gn/T/ipykernel_1017/1555375341.py:1: RuntimeWarning: This file contains raw Internal Active Shielding data. It may be distorted. Elekta recommends it be run through MaxFilter to produce reliable results. Consider closing the file and running MaxFilter on the data.
  run_04=mne.io.read_raw_fif('/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-04_meg.fif',allow_maxshield=True)


    Read a total of 13 projection items:
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
        generated with dossp-2.1 (1 x 306)  idle
    Range : 20000 ... 423999 =     20.000 ...   423.999 secs
Ready.
Reading 0 ... 403999  =      0.000 ...   403.999 secs...


/var/folders/14/1wp2gs4s4k9094qkx6kvfvq00000gn/T/ipykernel_1017/1555375341.py:2: RuntimeWarning: This file contains raw Internal Active Shielding data. It may be distorted. Elekta recommends it be run through MaxFilter to produce reliable results. Consider closing the file and running MaxFilter on the data.
  run_05=mne.io.read_raw_fif('/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS/sub-09/meg/sub-09_task-reproduction_run-05_meg.fif',allow_maxshield=True,preload=True)


In [9]:
rotation_matrix=run_04.info['dev_head_t']['trans']
det = np.linalg.det(rotation_matrix)
print(f"Determinant of rotation matrix: {det}")

Determinant of rotation matrix: 0.9998807112923436


In [11]:
cond = np.linalg.cond(rotation_matrix)
print(f"Condition number of rotation matrix: {cond}")

Condition number of rotation matrix: 4318.091786148612


In [ ]:
def extract_epoch_null_category(subject):
    """
    This function loads MEG fixation epochs for a given subject, crops them into three 500 ms epochs, 
    and returns the concatenated spatial epochs that could not be anticipated.

    Parameters:
    subject (str): The subject identifier (used to construct file path)

    Returns:
    mne.EpochsArray: A new EpochsArray containing three cropped epochs (each 500 ms long) concatenated vertically.
    """
    
    # Define the path to the preprocessed MEG epochs file based on the subject ID
    path = config.derivatives_path + 'fixation/sub-'+subject+'/meg/sub-'+subject+'_task-reproduction_epo.fif'
    
    # Load the MEG epochs from the file with preload enabled (data loaded into memory)
    epochs = mne.read_epochs(path, preload=True)
    
    # Concatenate the data from three cropped time intervals:
    # 1. From -1 to -0.5 seconds
    # 2. From -0.5 to 0 seconds
    # 3. From 0 to 0.5 seconds
    data = np.vstack([
        epochs.copy().crop(tmin=-1, tmax=-0.5).get_data(),  # First 500 ms epoch
        epochs.copy().crop(tmin=-0.5, tmax=0).get_data(),   # Second 500 ms epoch
        epochs.copy().crop(tmin=0, tmax=0.5).get_data()     # Third 500 ms epoch
    ])
    
    # Create a new EpochsArray object using the concatenated data and the original epochs' info
    epochs = mne.EpochsArray(data=data, info=epochs.copy().crop(tmin=0, tmax=0.5).info)

    # Return the new EpochsArray
    return epochs


In [ ]:
# -- Functions
def extract_epoch_null_category(subject):
    path = f'/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/derivatives/items/sub-{subject:02}/meg/sub-{subject:02}_task-reproduction_epo.fif'
    epochs= mne.read_epochs(path, preload=True)
    
    # -- Concatenate the data from three cropped time intervals:
    # 1. From -1 to -0.5 seconds
    # 2. From -0.5 to 0 seconds
    # 3. From 0 to 0.5 seconds
    data=np.vstack([
        epochs.copy().crop(tmin=-1,tmax=-0.5).get_data(),
        epochs.copy().crop(tmin=-0.5,tmax=0).get_data(),
        epochs.copy().crop(tmin=0, tmax=0.5).get_data()
    ])

    #
def extract_epochs_first_presentation

def create_training_epochs_7categories(subject):
    epochs_null=extract_epoch_null_category(subject)
    epochs_null.events[:,2]=99

    epochs_items=extract

In [17]:
sub=8
base_path='/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/derivatives/items/sub-08/meg'
items_epo_path=os.path.join(base_path,f'sub-08_task-reproduction_epo.fif')
fixation_epo_path='/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/derivatives/fixation/sub-08/meg/sub-08_task-reproduction_epo.fif'

In [19]:
items_epo=mne.read_epochs(items_epo_path,preload=True)

Reading /Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/derivatives/items/sub-08/meg/sub-08_task-reproduction_epo.fif ...
    Found the data of interest:
        t =    -192.00 ...     592.00 ms
        0 CTF compensation matrices available
Adding metadata with 58 columns
3240 matching events found
No baseline correction applied
0 projection items activated


In [43]:
np.unique(items_epo.events[:,2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54], dtype=int32)

In [15]:
# Get behavioral file: this is ground truth

# Load item based epochs (position 1,2,3,4,5,6)

# Load fixation based epochs (position 7 == nothing)

